<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ApiGatewayKit.Core.Shared</RootNamespace>
    <AssemblyName>ApiGatewayKit.Core.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

</Project>

